export const extendedPlaces = [
    // --- Thiruvananthapuram ---
    {
        name: "Padmanabhaswamy Temple",
        slug: "padmanabhaswamy-temple",
        district: "Thiruvananthapuram",
        location: "East Fort, Thiruvananthapuram",
        category: "Pilgrimage",
        description: "The Sree Padmanabhaswamy Temple is a Hindu temple dedicated to Lord Vishnu. It is considered the richest temple in the world and is a masterpiece of Dravidian and Kerala architectural styles.",
        image: "https://images.unsplash.com/photo-1629217861916-246eb7678177?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.4830,
        longitude: 76.9436,
        rating: 4.8,
        highlights: ["Richest Temple", "Dravidian Architecture", "Anantha Shayanam", "Mural Paintings"],
        bestTimeToVisit: "All year round",
        entryFee: "Free (Special Darshan Paid)",
        openingHours: "3:30 AM - 12:00 PM, 5:00 PM - 8:30 PM",
        ratingAvg: 4.8,
        images: ["https://images.unsplash.com/photo-1629217861916-246eb7678177?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["temple", "culture", "religious", "architecture"]
    },
    {
        name: "Varkala Cliff",
        slug: "varkala-cliff",
        district: "Thiruvananthapuram",
        location: "Varkala, Thiruvananthapuram",
        category: "Beach",
        description: "Varkala is the only place in southern Kerala where cliffs are found adjacent to the Arabian Sea. The beach is famous for its natural springs which are believed to have medicinal properties.",
        image: "https://images.unsplash.com/photo-1590050811270-e322662c919d?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.7379,
        longitude: 76.7163,
        rating: 4.7,
        highlights: ["Red Cliffs", "Papanasam Beach", "Paragliding", "Ayurveda Centers"],
        bestTimeToVisit: "September to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1590050811270-e322662c919d?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["beach", "cliff", "nature", "relaxation"]
    },
    {
        name: "Kovalam Beach",
        slug: "kovalam-beach",
        district: "Thiruvananthapuram",
        location: "Kovalam, Thiruvananthapuram",
        category: "Beach",
        description: "Kovalam is an internationally renowned beach with three adjacent crescent beaches. It has been a favorite haunt of tourists since the 1930s.",
        image: "https://images.unsplash.com/photo-1626297394991-38914c8106d4?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.4004,
        longitude: 76.9787,
        rating: 4.6,
        highlights: ["Lighthouse Beach", "Surfing", "Catamaran Ride", "Sunset Views"],
        bestTimeToVisit: "September to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1626297394991-38914c8106d4?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["beach", "lighthouse", "water-sports", "sunset"]
    },
    {
        name: "Ponmudi",
        slug: "ponmudi-hill-station",
        district: "Thiruvananthapuram",
        location: "Ponmudi, Thiruvananthapuram",
        category: "Hill Station",
        description: "A scenic hill station known for its mist-covered valleys, tea plantations, and winding roads with 22 hairpin bends.",
        image: "https://images.unsplash.com/photo-1595842878923-085734e56845?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.7599,
        longitude: 77.1167,
        rating: 4.5,
        highlights: ["Golden Valley", "Peppara Wildlife Sanctuary", "Trekking", "Mist"],
        bestTimeToVisit: "October to March",
        entryFee: "₹30",
        openingHours: "8:00 AM - 5:00 PM",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1595842878923-085734e56845?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["hill-station", "nature", "trekking", "viewpoint"]
    },

    // --- Kollam ---
    {
        name: "Jatayu Earth Center",
        slug: "jatayu-earth-center",
        district: "Kollam",
        location: "Chadayamangalam, Kollam",
        category: "Adventure",
        description: "Jatayu Earth Center hosts the world's largest bird sculpture. It is a rock-themed park built to promote mythology and adventure tourism.",
        image: "https://images.unsplash.com/photo-1625633498877-2c982346747b?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.8684,
        longitude: 76.8684,
        rating: 4.8,
        highlights: ["Largest Bird Sculpture", "Cable Car Ride", "Hilltop View", "Adventure Park"],
        bestTimeToVisit: "Morning or Evening",
        entryFee: "₹400 approx",
        openingHours: "10:00 AM - 8:00 PM",
        ratingAvg: 4.8,
        images: ["https://images.unsplash.com/photo-1625633498877-2c982346747b?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Moderate",
        tags: ["sculpture", "adventure", "mythology", "viewpoint"]
    },
    {
        name: "Munroe Island",
        slug: "munroe-island",
        district: "Kollam",
        location: "Munroe Island, Kollam",
        category: "Backwaters",
        description: "A hidden gem in the backwaters, Munroe Island offers serene canoe rides through narrow canals, mangrove arches, and village life.",
        image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.9950,
        longitude: 76.6111,
        rating: 4.7,
        highlights: ["Canoe Ride", "Mangrove Arch", "Village Life", "Sunrise"],
        bestTimeToVisit: "November to February",
        entryFee: "₹500 for Canoe",
        openingHours: "6:00 AM - 6:00 PM",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Moderate",
        tags: ["backwaters", "island", "nature", "village"]
    },
    {
        name: "Palaruvi Waterfalls",
        slug: "palaruvi-waterfalls",
        district: "Kollam",
        location: "Aryankavu, Kollam",
        category: "Nature",
        description: "One of the highest waterfalls in Kerala, known as 'Stream of Milk'. It cascades down from a height of 300 feet.",
        image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80",
        latitude: 8.9733,
        longitude: 77.1594,
        rating: 4.4,
        highlights: ["High Waterfall", "Forest Trek", "Picnic Spot", "Scenic Drive"],
        bestTimeToVisit: "June to January",
        entryFee: "₹25",
        openingHours: "8:00 AM - 4:00 PM",
        ratingAvg: 4.4,
        images: ["https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["waterfall", "nature", "forest"]
    },

    // --- Pathanamthitta ---
    {
        name: "Gavi",
        slug: "gavi",
        district: "Pathanamthitta",
        location: "Gavi, Pathanamthitta",
        category: "Nature",
        description: "Gavi is an eco-tourism spot known for its pristine beauty and wildlife. It is part of the Periyar Tiger Reserve and offers a great escape into nature.",
        image: "https://images.unsplash.com/photo-1542352352-019e3441bd64?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.4363,
        longitude: 77.1645,
        rating: 4.6,
        highlights: ["Jeep Safari", "Nature Walk", "Camping", "Wildlife Spotting"],
        bestTimeToVisit: "September to February",
        entryFee: "Permit Required",
        openingHours: "6:00 AM - 5:00 PM",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1542352352-019e3441bd64?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Moderate",
        tags: ["forest", "wildlife", "safari", "eco-tourism"]
    },
    {
        name: "Konni Elephant Reserve",
        slug: "konni-elephant-reserve",
        district: "Pathanamthitta",
        location: "Konni, Pathanamthitta",
        category: "Wildlife",
        description: "Famous for its elephant training center (Aanakoodu). Visitors can see elephants being trained and also take elephant rides.",
        image: "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.2456,
        longitude: 76.8485,
        rating: 4.5,
        highlights: ["Elephant Training", "Museum", "Bowl Boat Ride", "Nature"],
        bestTimeToVisit: "All year round",
        entryFee: "₹40",
        openingHours: "9:00 AM - 5:00 PM",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["elephant", "wildlife", "family"]
    },

    // --- Alappuzha ---
    {
        name: "Alappuzha Backwaters",
        slug: "alappuzha-backwaters",
        district: "Alappuzha",
        location: "Alappuzha",
        category: "Backwaters",
        description: "Famous as the 'Venice of the East', Alleppey offers enchanting houseboat cruises through lush green paddy fields and coconut groves.",
        image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.4981,
        longitude: 76.3388,
        rating: 4.9,
        highlights: ["Houseboats", "Snake Boat Race", "Paddy Fields", "Canal Cruise"],
        bestTimeToVisit: "September to March",
        entryFee: "Varies by boat",
        openingHours: "24/7",
        ratingAvg: 4.9,
        images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Expensive",
        tags: ["backwaters", "houseboat", "romantic", "cruise"]
    },
    {
        name: "Kuttanad",
        slug: "kuttanad",
        district: "Alappuzha",
        location: "Kuttanad, Alappuzha",
        category: "Nature",
        description: "Kuttanad, the 'Rice Bowl of Kerala', is unique for farming below sea level. It offers scenic views of endless paddy fields and waterways.",
        image: "https://images.unsplash.com/photo-1593693396818-32544710cc9c?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.3888,
        longitude: 76.4740,
        rating: 4.7,
        highlights: ["Below Sea Level Farming", "Rural Life", "Scenic Canals", "Warm Hospitality"],
        bestTimeToVisit: "August to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1593693396818-32544710cc9c?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["nature", "farming", "village", "landscape"]
    },
    {
        name: "Marari Beach",
        slug: "marari-beach",
        district: "Alappuzha",
        location: "Mararikulam, Alappuzha",
        category: "Beach",
        description: "A peaceful and undeveloped beach perfect for relaxation. It offers a glimpse into traditional fishing village life.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.6006,
        longitude: 76.2995,
        rating: 4.6,
        highlights: ["Clean Sand", "Quiet Atmosphere", "Fishing Village", "Sunset"],
        bestTimeToVisit: "September to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["beach", "quiet", "relaxation"]
    },

    // --- Kottayam ---
    {
        name: "Kumarakom Bird Sanctuary",
        slug: "kumarakom-bird-sanctuary",
        district: "Kottayam",
        location: "Kumarakom, Kottayam",
        category: "Nature",
        description: "Located on the banks of Vembanad Lake, this sanctuary is a favorite haunt of migratory birds like the Siberian Stork.",
        image: "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.6256,
        longitude: 76.4253,
        rating: 4.5,
        highlights: ["Migratory Birds", "Boating", "Butterfly Garden", "Nature Trails"],
        bestTimeToVisit: "November to February",
        entryFee: "₹50",
        openingHours: "6:00 AM - 6:00 PM",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["birds", "wildlife", "nature", "lake"]
    },
    {
        name: "Ilaveezhapoonchira",
        slug: "ilaveezhapoonchira",
        district: "Kottayam",
        location: "Melukavu, Kottayam",
        category: "Hill Station",
        description: "A beautiful hill station surrounded by three hillocks. Known for its spectacular sunrise and sunset views.",
        image: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.8080,
        longitude: 76.7865,
        rating: 4.6,
        highlights: ["Sunrise View", "Trekking", "Off-road Drive", "No Trees"],
        bestTimeToVisit: "August to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["hill-station", "sunrise", "trekking"]
    },

    // --- Idukki ---
    {
        name: "Munnar Tea Gardens",
        slug: "munnar-tea-gardens",
        district: "Idukki",
        location: "Munnar, Idukki",
        category: "Hill Station",
        description: "South India's most popular hill station, famous for tea plantations, misty hills, and the Neelakurinji flower.",
        image: "https://images.unsplash.com/photo-1593693396818-32544710cc9c?auto=format&fit=crop&w=1200&q=80",
        latitude: 10.0889,
        longitude: 77.0595,
        rating: 4.9,
        highlights: ["Tea Gardens", "Eravikulam Park", "Mattupetty Dam", "Cool Climate"],
        bestTimeToVisit: "September to March",
        entryFee: "Varies",
        openingHours: "9:00 AM - 5:00 PM",
        ratingAvg: 4.9,
        images: ["https://images.unsplash.com/photo-1593693396818-32544710cc9c?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["tea", "nature", "hills", "romantic"]
    },
    {
        name: "Thekkady (Periyar)",
        slug: "thekkady-periyar",
        district: "Idukki",
        location: "Kumily, Idukki",
        category: "Wildlife",
        description: "Home to Periyar Tiger Reserve, Thekkady offers boat rides where you can spot wild elephants and diverse fauna in their natural habitat.",
        image: "https://images.unsplash.com/photo-1596701837130-1c3127883445?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.6031,
        longitude: 77.1615,
        rating: 4.6,
        highlights: ["Periyar Lake Boat Ride", "Elephant Safari", "Spice Walk", "Tiger Reserve"],
        bestTimeToVisit: "September to March",
        entryFee: "₹400 approx",
        openingHours: "6:00 AM - 5:00 PM",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1596701837130-1c3127883445?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Moderate",
        tags: ["wildlife", "safari", "nature", "tiger"]
    },
    {
        name: "Vagamon",
        slug: "vagamon-meadows",
        district: "Idukki",
        location: "Vagamon, Idukki",
        category: "Hill Station",
        description: "A peaceful hill destination with green meadows, pine forests, and a cool climate. Less crowded than Munnar.",
        image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.6841,
        longitude: 76.9056,
        rating: 4.7,
        highlights: ["Pine Forest", "Meadows", "Paragliding", "Thangal Para"],
        bestTimeToVisit: "All year round",
        entryFee: "₹20",
        openingHours: "8:00 AM - 6:00 PM",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["hill-station", "meadows", "quiet", "nature"]
    },

    // --- Ernakulam ---
    {
        name: "Fort Kochi",
        slug: "fort-kochi",
        district: "Ernakulam",
        location: "Fort Kochi",
        category: "History",
        description: "A historical melting pot with colonial architecture, Chinese fishing nets, and a vibrant arts scene. It reflects Portuguese, Dutch, and British influences.",
        image: "https://images.unsplash.com/photo-1591528652399-6e32d665793e?auto=format&fit=crop&w=1200&q=80",
        latitude: 9.9656,
        longitude: 76.2421,
        rating: 4.5,
        highlights: ["Chinese Fishing Nets", "St. Francis Church", "Jew Town", "Mattancherry Palace"],
        bestTimeToVisit: "October to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1591528652399-6e32d665793e?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["history", "art", "culture", "colonial"]
    },
    {
        name: "Wonderla Kochi",
        slug: "wonderla-kochi",
        district: "Ernakulam",
        location: "Pallikkara, Ernakulam",
        category: "Adventure",
        description: "The largest water theme park in Kerala, offering a wide variety of exhilarating water and land rides.",
        image: "https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=1200&q=80",
        latitude: 10.0261,
        longitude: 76.3989,
        rating: 4.6,
        highlights: ["High Thrill Rides", "Water Slides", "Wave Pool", "Family Fun"],
        bestTimeToVisit: "All year round",
        entryFee: "₹1200 approx",
        openingHours: "11:00 AM - 6:00 PM",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Expensive",
        tags: ["theme-park", "fun", "kids", "water-park"]
    },
    {
        name: "Hill Palace Museum",
        slug: "hill-palace-museum",
        district: "Ernakulam",
        location: "Tripunithura, Ernakulam",
        category: "History",
        description: "The largest archaeological museum in Kerala, formerly the imperial administrative office and official residence of Cochin Maharaja.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Hill_Palace_Museum_Thripunithura.jpg",
        latitude: 9.9535,
        longitude: 76.3621,
        rating: 4.4,
        highlights: ["Royal Artifacts", "Deer Park", "Heritage Building", "History"],
        bestTimeToVisit: "All year round",
        entryFee: "₹30",
        openingHours: "9:00 AM - 4:30 PM (Mondays Closed)",
        ratingAvg: 4.4,
        images: ["https://upload.wikimedia.org/wikipedia/commons/8/87/Hill_Palace_Museum_Thripunithura.jpg"],
        priceLevel: "Cheap",
        tags: ["museum", "history", "royal", "culture"]
    },

    // --- Thrissur ---
    {
        name: "Athirappilly Waterfalls",
        slug: "athirappilly-falls",
        district: "Thrissur",
        location: "Athirappilly, Thrissur",
        category: "Nature",
        description: "Known as the 'Niagara of India', this 80-foot high waterfall is a majestic sight, especially during the monsoon.",
        image: "https://images.unsplash.com/photo-1622306354802-5e434440539c?auto=format&fit=crop&w=1200&q=80",
        latitude: 10.2851,
        longitude: 76.5698,
        rating: 4.8,
        highlights: ["Niagara of India", "Rainforest", "Baahubali Film Site", "Trekking"],
        bestTimeToVisit: "June to January",
        entryFee: "₹50",
        openingHours: "8:00 AM - 6:00 PM",
        ratingAvg: 4.8,
        images: ["https://images.unsplash.com/photo-1622306354802-5e434440539c?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["waterfall", "nature", "scenic", "film-location"]
    },
    {
        name: "Thrissur Zoo & Museum",
        slug: "thrissur-zoo",
        district: "Thrissur",
        location: "Chembukkavu, Thrissur",
        category: "Culture",
        description: "One of the oldest zoos in the country, home to a wide variety of animals, reptiles, and birds. Also houses a natural history museum.",
        image: "https://images.unsplash.com/photo-1559253664-b2649ba8ad20?auto=format&fit=crop&w=1200&q=80",
        latitude: 10.5303,
        longitude: 76.2205,
        rating: 4.2,
        highlights: ["Wildlife", "Art Museum", "Botanical Garden", "Family Outing"],
        bestTimeToVisit: "All year round",
        entryFee: "₹20",
        openingHours: "10:00 AM - 5:00 PM (Mondays Closed)",
        ratingAvg: 4.2,
        images: ["https://images.unsplash.com/photo-1559253664-b2649ba8ad20?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["zoo", "animals", "museum", "family"]
    },
    {
        name: "Vadakkunnathan Temple",
        slug: "vadakkunnathan-temple",
        district: "Thrissur",
        location: "Thrissur City",
        category: "Pilgrimage",
        description: "An ancient Shiva temple with classic Kerala style architecture, featuring monumental towers and mural paintings.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Vadakkunnathan_Temple_Thrissur_Kerala_India.jpg",
        latitude: 10.5244,
        longitude: 76.2136,
        rating: 4.7,
        highlights: ["Classic Architecture", "Mural Paintings", "Thrissur Pooram Venue", "Sprawling Grounds"],
        bestTimeToVisit: "April (Pooram Festival)",
        entryFee: "Free",
        openingHours: "4:00 AM - 10:00 AM, 5:00 PM - 8:30 PM",
        ratingAvg: 4.7,
        images: ["https://upload.wikimedia.org/wikipedia/commons/d/d3/Vadakkunnathan_Temple_Thrissur_Kerala_India.jpg"],
        priceLevel: "Free",
        tags: ["temple", "shiva", "architecture", "religious"]
    },

    // --- Palakkad ---
    {
        name: "Silent Valley National Park",
        slug: "silent-valley",
        district: "Palakkad",
        location: "Mannarkkad, Palakkad",
        category: "Nature",
        description: "One of the last remaining rainforests in the Western Ghats, known for its rich biodiversity and the absence of cicadas.",
        image: "https://images.unsplash.com/photo-1448375240586-dfd8d395ea6c?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.1309,
        longitude: 76.4258,
        rating: 4.6,
        highlights: ["Rainforest", "Biodiversity", "Lion-tailed Macaque", "Trekking"],
        bestTimeToVisit: "December to April",
        entryFee: "₹50 (plus Jeep)",
        openingHours: "8:00 AM - 1:00 PM",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1448375240586-dfd8d395ea6c?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["forest", "wildlife", "nature", "trekking"]
    },
    {
        name: "Malampuzha Dam",
        slug: "malampuzha-dam",
        district: "Palakkad",
        location: "Malampuzha, Palakkad",
        category: "Adventure",
        description: "A large irrigation dam with a beautiful garden, a ropeway ride, and the famous Yakshi sculpture.",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Malampuzha_Dam_and_Garden.jpg",
        latitude: 10.8306,
        longitude: 76.6811,
        rating: 4.4,
        highlights: ["Ropeway", "Rock Garden", "Yakshi Statue", "Boating"],
        bestTimeToVisit: "August to March",
        entryFee: "₹25",
        openingHours: "9:00 AM - 8:00 PM",
        ratingAvg: 4.4,
        images: ["https://upload.wikimedia.org/wikipedia/commons/f/ff/Malampuzha_Dam_and_Garden.jpg"],
        priceLevel: "Cheap",
        tags: ["dam", "garden", "family", "picnic"]
    },

    // --- Kozhikode ---
    {
        name: "Kappad Beach",
        slug: "kappad-beach",
        district: "Kozhikode",
        location: "Kappad, Kozhikode",
        category: "Beach",
        description: "A historic beach where Vasco da Gama landed in 1498, marking the beginning of the spice route effectively.",
        image: "https://images.unsplash.com/photo-1621683407981-6782299d6386?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.3891,
        longitude: 75.7177,
        rating: 4.4,
        highlights: ["History", "Stone Monument", "Clean Beach", "Sunset"],
        bestTimeToVisit: "October to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.4,
        images: ["https://images.unsplash.com/photo-1621683407981-6782299d6386?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["beach", "history", "sunset"]
    },
    {
        name: "Kozhikode Beach",
        slug: "kozhikode-beach",
        district: "Kozhikode",
        location: "Kozhikode City",
        category: "Beach",
        description: "A popular beach known for its sunsets, old pier crumbling into the sea, and delicious street food like Kallumakkaya.",
        image: "https://images.unsplash.com/photo-1625633498877-2c982346747b?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.2626,
        longitude: 75.7673,
        rating: 4.5,
        highlights: ["Sunset", "Old Pier", "Street Food", "Dolphins"],
        bestTimeToVisit: "September to March",
        entryFee: "Free",
        openingHours: "24/7",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1625633498877-2c982346747b?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Free",
        tags: ["beach", "food", "city", "sunset"]
    },

    // --- Wayanad ---
    {
        name: "Edakkal Caves",
        slug: "edakkal-caves",
        district: "Wayanad",
        location: "Nenmenil, Wayanad",
        category: "History",
        description: "Two natural caves featuring prehistoric petroglyphs (rock carvings) dating back to 6000 BC, providing evidence of early human settlement.",
        image: "https://images.unsplash.com/photo-1627915939223-9f8c6b772e27?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.6322,
        longitude: 76.2366,
        rating: 4.5,
        highlights: ["Prehistoric Carvings", "Trekking", "View Point", "History"],
        bestTimeToVisit: "October to May",
        entryFee: "₹30",
        openingHours: "9:30 AM - 4:00 PM (Closed Mondays)",
        ratingAvg: 4.5,
        images: ["https://images.unsplash.com/photo-1627915939223-9f8c6b772e27?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["caves", "history", "trekking", "viewpoint"]
    },
    {
        name: "Banasura Sagar Dam",
        slug: "banasura-sagar",
        district: "Wayanad",
        location: "Padinjarathara, Wayanad",
        category: "Adventure",
        description: "The largest earth dam in India and the second largest in Asia. The reservoir features islands that are hauntingly beautiful.",
        image: "https://images.unsplash.com/photo-1597825064619-33b5c3e53616?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.6687,
        longitude: 75.9555,
        rating: 4.6,
        highlights: ["Speed Boating", "Trekking", "Scenic Views", "Islands"],
        bestTimeToVisit: "September to March",
        entryFee: "₹40",
        openingHours: "9:00 AM - 5:00 PM",
        ratingAvg: 4.6,
        images: ["https://images.unsplash.com/photo-1597825064619-33b5c3e53616?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["dam", "boating", "nature", "scenic"]
    },
    {
        name: "Chembra Peak",
        slug: "chembra-peak",
        district: "Wayanad",
        location: "Meppadi, Wayanad",
        category: "Adventure",
        description: "The highest peak in Wayanad, famous for its heart-shaped lake halfway to the top.",
        image: "https://images.unsplash.com/photo-1502476563600-94639908de75?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.5361,
        longitude: 76.0841,
        rating: 4.7,
        highlights: ["Heart Shaped Lake", "Trekking", "Panoramic View", "Nature"],
        bestTimeToVisit: "September to February",
        entryFee: "₹50 (plus Trekking fee)",
        openingHours: "7:00 AM - 5:00 PM",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1502476563600-94639908de75?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["trekking", "mountain", "viewpoint", "lake"]
    },

    // --- Kannur ---
    {
        name: "Muzhappilangad Drive-in Beach",
        slug: "muzhappilangad-beach",
        district: "Kannur",
        location: "Muzhappilangad, Kannur",
        category: "Beach",
        description: "Asia's longest drive-in beach, offering a unique experience of driving along the 4km coastline.",
        image: "https://images.unsplash.com/photo-1632829286438-232128a3952f?auto=format&fit=crop&w=1200&q=80",
        latitude: 11.7922,
        longitude: 75.4497,
        rating: 4.7,
        highlights: ["Drive-in Beach", "Water Sports", "Beach Festival", "Sunset Drive"],
        bestTimeToVisit: "September to May",
        entryFee: "₹50 per car",
        openingHours: "24/7",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1632829286438-232128a3952f?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["beach", "drive-in", "adventure", "fun"]
    },
    {
        name: "St. Angelo Fort",
        slug: "st-angelo-fort",
        district: "Kannur",
        location: "Kannur City",
        category: "History",
        description: "A massive triangular laterite fort backed by the sea, built by the Portuguese in 1505. Offers great views of the Mappila Bay.",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/13/St._Angelo_Fort_Kannur.jpg",
        latitude: 11.8540,
        longitude: 75.3725,
        rating: 4.5,
        highlights: ["Portuguese architecture", "Sea view", "History", "Walkways"],
        bestTimeToVisit: "September to May",
        entryFee: "₹25",
        openingHours: "8:00 AM - 5:30 PM",
        ratingAvg: 4.5,
        images: ["https://upload.wikimedia.org/wikipedia/commons/1/13/St._Angelo_Fort_Kannur.jpg"],
        priceLevel: "Cheap",
        tags: ["history", "fort", "sea", "architecture"]
    },

    // --- Kasaragod ---
    {
        name: "Bekal Fort",
        slug: "bekal-fort",
        district: "Kasaragod",
        location: "Bekal, Kasaragod",
        category: "History",
        description: "The largest fort in Kerala, offering stunning views of the Arabian Sea. It's a key historical landmark appearing in many movies.",
        image: "https://images.unsplash.com/photo-1614761044391-4c6439066606?auto=format&fit=crop&w=1200&q=80",
        latitude: 12.3839,
        longitude: 75.0333,
        rating: 4.7,
        highlights: ["Largest Fort", "Sea View", "Observation Tower", "Beach Park"],
        bestTimeToVisit: "October to March",
        entryFee: "₹25",
        openingHours: "8:00 AM - 5:30 PM",
        ratingAvg: 4.7,
        images: ["https://images.unsplash.com/photo-1614761044391-4c6439066606?auto=format&fit=crop&w=1200&q=80"],
        priceLevel: "Cheap",
        tags: ["fort", "history", "viewpoint", "sea"],
        status: "approved"
    }
];
